version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: trinhpham/mysql-backup-to-cloud
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
  publish-latest:
    environment:
      IMAGE_NAME: trinhpham/mysql-backup-to-cloud
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          context:
            # The context that holds DOCKERHUB_USERNAME and DOCKERHUB_PASS
            - DockerHub
          requires:
            - build
          filters:
            branches:
              only: master
