version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: trinhpham/mysql-backup-to-cloud
      IMAGE_VERSION: 3.0
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG="$IMAGE_VERSION.${CIRCLE_BUILD_NUM}"
            echo "Begin push $IMAGE_NAME:$IMAGE_TAG"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          context:
            # The context that holds DOCKERHUB_USERNAME and DOCKERHUB_PASS
            - DockerHub
          filters:
            branches:
              only: master
